import type { Metadata } from 'next';
import Providers from './providers';
import { AppInitializer } from '@/hoc/AppInitializer';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppInitializer>
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </AppInitializer>
      </body>
    </html>
  );
}
